version: '3.8'
services: 
  db-mysql:
    container_name: db-mysql
    image: 'mysql:8.0'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  symfony:
    container_name: symfony
    build:
      context: .
    ports:
      - '8000:8000'
    volumes:
      - ./app:/var/www/symfony
    depends_on:
      - db-mysql
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/symfony
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - symfony
      - db-mysql